application: eprint-updates
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron
  script: web.app
  login: admin
  secure: always

- url: /test
  script: web.app
  login: admin
  secure: always

- url: /(.*\.(js|css))
  static_files: static/\1
  upload: static/(.*\.(js|css))
  secure: always

- url: /.*
  static_files: static/index.html
  upload: static/index.html
  secure: always
