application: eprint-updates
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /hourly
  script: web.app
  login: admin

- url: /test
  script: web.app
  login: admin

- url: /.*
  script: web.app
